In [1]:
import numpy as np 

**NUMPY INDEXING AND SLICING OF VECTORS**

In [35]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [37]:
arr[4]

np.int64(15)

In [38]:
arr[1:6]

array([12, 13, 14, 15, 16])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [39]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [41]:
arr= np.arange(0,150).reshape(15,10)
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]])

In [52]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
arr[0,6]

np.int64(6)

In [56]:
arr[1:5,1:5]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [57]:
arr[0:6,1:5]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54]])

In [58]:
arr[4:8,3:9]

array([[43, 44, 45, 46, 47, 48],
       [53, 54, 55, 56, 57, 58],
       [63, 64, 65, 66, 67, 68],
       [73, 74, 75, 76, 77, 78]])

In [59]:
sl = arr[1:4,1:5]
sl

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [60]:
arr[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [61]:
arr[:,2]

array([  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102, 112, 122,
       132, 142])

**BOOLEAN INDEXING**

In [62]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [65]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])